// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuz8N991RzdYtvVGX56Pk2Bz0e-KFR5ws',
    appId: '1:645558362381:web:6cc1a8973544fc47989044',
    messagingSenderId: '645558362381',
    projectId: 'expense-tracker-2071a',
    authDomain: 'expense-tracker-2071a.firebaseapp.com',
    storageBucket: 'expense-tracker-2071a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-zrCGmSdN0ZkPP85e6qM2eCxjitTHRU0',
    appId: '1:645558362381:android:b459a2f81a31c9fd989044',
    messagingSenderId: '645558362381',
    projectId: 'expense-tracker-2071a',
    storageBucket: 'expense-tracker-2071a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-4IuZW2P1rdLIhhdRggr8geHNzxmaEEQ',
    appId: '1:645558362381:ios:4e7bd44e89e030e3989044',
    messagingSenderId: '645558362381',
    projectId: 'expense-tracker-2071a',
    storageBucket: 'expense-tracker-2071a.appspot.com',
    iosClientId: '645558362381-jr2kaf48i458vi2oa0um19bo7i0nqjk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-4IuZW2P1rdLIhhdRggr8geHNzxmaEEQ',
    appId: '1:645558362381:ios:4e7bd44e89e030e3989044',
    messagingSenderId: '645558362381',
    projectId: 'expense-tracker-2071a',
    storageBucket: 'expense-tracker-2071a.appspot.com',
    iosClientId: '645558362381-jr2kaf48i458vi2oa0um19bo7i0nqjk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensTracker',
  );
}
